# Generated by Django 2.2.6 on 2020-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=10)),
                ('offers', models.CharField(max_length=1000)),
                ('socket_id', models.CharField(max_length=100)),
            ],
        ),
    ]
