# Generated by Django 2.2.6 on 2020-03-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socinfo',
            name='account_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socinfo',
            name='offers',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
