# Generated by Django 2.2.6 on 2019-10-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191025_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='fff', max_length=100),
            preserve_default=False,
        ),
    ]
