# Generated by Django 2.2.6 on 2019-10-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191029_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('RG', 'Regular'), ('PR', 'Premium')], default='RG', max_length=2),
        ),
    ]
