# Generated by Django 2.2.6 on 2019-11-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(help_text='Auto generated', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('RG', 'Regular'), ('PR', 'Premium'), ('DM', 'Demo')], default='DM', max_length=2),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=7)),
                ('action', models.CharField(choices=[('BY', 'Buy'), ('SL', 'Sell')], max_length=3)),
                ('timeframe', models.CharField(choices=[('D', 'Day'), ('4H', '4-Hour'), ('H', 'Hour'), ('30M', 'Minutes')], max_length=4)),
                ('atr', models.FloatField()),
                ('min_lot', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('expiry', models.DateTimeField(auto_now=True)),
                ('generator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='account.SignalGenerator')),
            ],
        ),
    ]
