# Generated by Django 2.2.6 on 2019-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191101_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalgenerator',
            name='token',
            field=models.CharField(blank=True, help_text='Auto generated', max_length=100),
        ),
    ]
