# Generated by Django 2.2.6 on 2019-11-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191101_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='expiry',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
