# Generated by Django 2.2.6 on 2019-11-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191101_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
