# Generated by Django 2.2.6 on 2019-11-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191101_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='expiry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
