# Generated by Django 2.2.6 on 2019-11-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191102_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
