# Generated by Django 2.2.6 on 2019-11-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20191102_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalgenerator',
            name='token',
            field=models.CharField(blank=True, help_text='Auto generated', max_length=100),
        ),
    ]
