# Generated by Django 2.2.6 on 2019-11-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20191102_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signal',
        ),
        migrations.DeleteModel(
            name='SignalGenerator',
        ),
    ]
