# Generated by Django 2.2.6 on 2019-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191102_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
