# Generated by Django 2.2.6 on 2019-11-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_account_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], max_length=2)),
                ('deposit_type', models.CharField(choices=[('mtn', 'MTN'), ('visa', 'Visa')], max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deposits', to='account.Account')),
            ],
        ),
    ]
