# Generated by Django 2.2.6 on 2019-11-13 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='updated',
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposited',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='withdrawals', to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PendingWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('withdrawn', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pending_withdrawals', to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PendingDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('deposit_type', models.CharField(choices=[('mtn', 'MTN'), ('visa', 'Visa')], max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pending_deposits', to='account.Account')),
            ],
        ),
    ]
