# Generated by Django 2.2.6 on 2019-11-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20191113_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingwithdrawal',
            name='withdrawn',
        ),
        migrations.AddField(
            model_name='pendingwithdrawal',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingwithdrawal',
            name='withdraw_type',
            field=models.CharField(choices=[('mtn', 'MTN'), ('voda', 'Vodafone')], default='mtn', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawn',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingdeposit',
            name='deposit_type',
            field=models.CharField(choices=[('mtn', 'MTN'), ('visa', 'Visa')], max_length=6),
        ),
    ]
