# Generated by Django 2.2.6 on 2019-11-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20191113_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingwithdrawal',
            old_name='withdraw_type',
            new_name='withdrawal_type',
        ),
    ]
