# Generated by Django 2.2.6 on 2019-11-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20191113_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_type',
            field=models.CharField(choices=[('mtn', 'MTN'), ('voda', 'Vodafone')], default='mtn', max_length=6),
            preserve_default=False,
        ),
    ]
