# Generated by Django 2.2.6 on 2019-11-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='expiry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
