# Generated by Django 2.2.6 on 2019-11-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_signal_bars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='bars',
        ),
        migrations.AlterField(
            model_name='signal',
            name='expiry',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
