# Generated by Django 2.2.6 on 2019-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_auto_20191103_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='bars',
            field=models.TextField(default='[[1,2]]'),
            preserve_default=False,
        ),
    ]
