# Generated by Django 2.2.6 on 2019-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_auto_20191103_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalgenerator',
            name='generator_type',
            field=models.CharField(choices=[('R', 'Regular'), ('P', 'Premium')], default='R', max_length=5),
        ),
    ]
