# Generated by Django 2.2.6 on 2019-11-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_signalgenerator_generator_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='atr',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='min_lot',
        ),
    ]
