# Generated by Django 2.2.6 on 2020-02-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0010_auto_20200131_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='pip_value',
        ),
    ]
