# Generated by Django 2.2.6 on 2020-02-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_auto_20200226_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='timeframe',
            field=models.CharField(choices=[('D1', '1Day'), ('H4', '4Hour'), ('H1', '1Hour'), ('M30', '30Minutes'), ('M15', '15Minutes')], max_length=4),
        ),
    ]
