# Generated by Django 2.2.6 on 2019-11-09 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0008_auto_20191109_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_size', models.FloatField()),
                ('risk', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('stoploss_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('previous_price', models.FloatField()),
                ('profit', models.FloatField()),
                ('stop_loss_profit', models.FloatField()),
                ('status', models.CharField(choices=[('Open', 'O'), ('Closed', 'C')], max_length=3)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trades', to='signals.Signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
