# Generated by Django 2.2.6 on 2019-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
