# Generated by Django 2.2.6 on 2019-11-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='stop_loss_profit',
            new_name='stoploss_profit',
        ),
    ]
