# Generated by Django 2.2.6 on 2020-01-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20191112_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='order_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
