# Generated by Django 2.2.6 on 2020-02-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_trade_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='order_id',
            new_name='trade_id',
        ),
    ]
