# Generated by Django 2.2.6 on 2020-02-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_auto_20200221_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('PO', 'Pending_Open'), ('PC', 'Pending_Close'), ('A', 'Attempted'), ('E', 'Error')], max_length=3),
        ),
    ]
