# Generated by Django 2.2.6 on 2020-02-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_auto_20200221_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('PO', 'Pending_Open'), ('PC', 'Pending_Close'), ('AO', 'Attempted_Open'), ('AC', 'Attempted_Close'), ('E', 'Error')], max_length=3),
        ),
    ]
